### ISSUE TITLE
Some Ideas

### ISSUE THREAD

**Issue by floranf** [nylo-andry/pomodori#3]
Add remaining time in the tab or window title
Add sound to the notification
Add warning if you are about to leave the pomodori tab/window

**Comment by fvnilo** [comment]
I just added the warning when someone tries to leave the page.

The rest of your ideas will be implemented soon.

**Comment by fvnilo** [comment]
update of title is done

**Comment by floranf** [comment]
Just tested the point 1 and 3 and it works nicely. Thanks
